# Generated by Django 4.2 on 2026-05-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show')], default='movie', max_length=10)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('wishlist', 'Wishlist'), ('watching', 'Watching'), ('completed', 'Completed')], default='wishlist', max_length=20)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('total_episodes', models.IntegerField(blank=True, null=True)),
                ('episodes_watched', models.IntegerField(blank=True, null=True)),
                ('episode_duration', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
