# Generated by Django 4.2 on 2026-05-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='status',
            field=models.CharField(choices=[('wishlist', 'Wishlist'), ('watching', 'Watching'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='wishlist', max_length=20),
        ),
    ]
